schemaVersion: 1
sessionDefaults:
  projectPath: /Users/PrinceTyga/Documents/development/for_human_review_apps/Pattern
    Breaker/Pattern Breaker.xcodeproj
  scheme: Pattern Breaker
  simulatorId: 4BFBF65C-C579-4F81-937B-57996034FAD1
  simulatorPlatform: iOS Simulator
  simulatorName: iPhone 17
